DEFAULT_FILE_TYPES = {
    '.php': 'php',
    '.c': 'clike',
    '.h': 'clike',
    '.cpp': 'clike',
    '.m': 'clike',
    '.mm': 'clike',
    '.ino': 'clike',
    '.cs': 'text/x-csharp',
    '.java': 'text/x-java',
    '.clj': 'clojure',
    '.coffee': 'coffeescript',
    '.css': 'css',
    '.diff': 'diff',
    '.ecl': 'ecl',
    '.el': 'erlang',
    '.go': 'go',
    '.groovy': 'groovy',
    '.hs': 'haskell',
    '.lhs': 'haskell',
    '.jsp': 'htmlembedded',
    '.asp': 'htmlembedded',
    '.aspx': 'htmlembedded',
    '.html': 'htmlmixed',
    '.tpl': 'htmlmixed',
    '.js': 'javascript',
    '.json': 'javascript',
    '.less': 'less',
    '.lua': 'lua',
    '.md': 'markdown',
    '.markdown': 'markdown',
    '.sql': 'mysql',
    '.ml': 'ocaml',
    '.mli': 'ocaml',
    '.pl': 'perl',
    '.pm': 'perl',
    '.pas': 'pascal',
    '.ini': 'properties',
    '.cfg': 'properties',
    '.nt': 'ntriples',
    '.py': 'python',
    '.rb': 'ruby',
    '.rst': 'rst',
    '.r': 'r',
    '.sh': 'shell',
    '.ss': 'scheme',
    '.scala': 'text/x-scala',
    '.scm': 'scheme',
    '.sls': 'scheme',
    '.sps': 'scheme',
    '.rs': 'rust',
    '.st': 'smalltalk',
    '.tex': 'stex',
    '.vbs': 'vbscript',
    '.vb': 'vbscript',
    '.v': 'verilog',
    '.xml': 'xml',
    '.xsd': 'xml',
    '.xsl': 'xml',
    '.xul': 'xml',
    '.xlf': 'xml',
    '.xliff': 'xml',
    '.xaml': 'xml',
    '.wxs': 'xml',
    '.wxl': 'xml',
    '.wxi': 'xml',
    '.wsdl': 'xml',
    '.svg': 'xml',
    '.rss': 'xml',
    '.rdf': 'xml',
    '.plist': 'xml',
    '.mxml': 'xml',
    '.kml': 'xml',
    '.glade': 'xml',
    '.xq': 'xquery',
    '.xqm': 'xquery',
    '.xquery': 'xquery',
    '.xqy': 'xquery',
    '.yml': 'yaml',
    '.yaml': 'yaml',
    '.png': 'image',
    '.jpg': 'image',
    '.gif': 'image',
    '.jpeg': 'image',
    '.bmp': 'image',
    '.csproj': 'xml',
}

DEFAULT_BINARY_TYPES = (
    'exe', 'com', 'so', 'la', 'o', 'dll', 'pyc',
    'jpg', 'jpeg', 'bmp', 'gif', 'png', 'xmp', 'pcx', 'svgz', 'ttf', 'tiff', 'oet',
    'gz', 'tar', 'rar', 'zip', '7z', 'jar', 'class',
    'odt', 'ods', 'pdf', 'doc', 'docx', 'dot', 'xls', 'xlsx',
)
